[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/#/*"
  to = "/admin/index.html"
  status = 200

[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"