backend:
  name: git-gateway
  branch: main
  identity_url: https://grupo-di.netlify.app/.netlify/identity
  gateway_url: https://grupo-di.netlify.app/.netlify/git
  repo: NicolasPabloSoto/grupo-di  # Este es tu repositorio en GitHub

media_folder: "public/uploads"  # Donde se guardarán los archivos de media en Netlify CMS
public_folder: "/uploads"  # La URL pública de los archivos

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"  # Carpeta donde están los posts en Markdown
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
