backend:
  name: git-gateway
  branch: main
  identity_url: https://grupo-di.netlify.app/.netlify/identity
  gateway_url: https://grupo-di.netlify.app/.netlify/git
  repo: https://github.com/NicolasPabloSoto/grupo-di

media_folder: "public/uploads" # Carpeta donde se guardan los archivos multimedia
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
