backend:
  name: git-gateway
  branch: main
  identity_url: https://grupo-di.netlify.app/.netlify/identity
  gateway_url: https://grupo-di.netlify.app/.netlify/git
  repo: NicolasPabloSoto/grupo-di  # Reemplaza con tu repositorio correcto

media_folder: "public/uploads"  # Carpeta donde se almacenan las imágenes subidas
public_folder: "/uploads"  # Carpeta pública para acceder a las imágenes

media_library:
  name: "file-system"  # Nombre para indicar que se usa el sistema de archivos local
  config:
    media_folder: "public/uploads"  # Carpeta donde se almacenarán las imágenes
    public_folder: "/uploads"       # URL pública de las imágenes


collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
